version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=latte
      - POSTGRES_PASSWORD=latte
      - POSTGRES_DB=frappuccino
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  s3:
    build: ./S3
    ports:
      - "9000:9000"
    environment:
      - STORAGE_PATH=/data

    volumes:
      - s3-data:/data  # Changed from bind mount to named volume
    user: "1000:1000"  # Run as non-root user
    
  app:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=latte
      - DB_PASSWORD=latte
      - DB_NAME=frappuccino
      - DB_PORT=5432
    depends_on:
      - db
      - s3
volumes:
  s3-data: